#端口
server:
  port: 8060
  servlet:
    context-path: /zwkj
spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
      url: jdbc:mysql://rm-bp1cskknfvfcrtf9e6o.mysql.rds.aliyuncs.com:3306/zwmds?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: zwmds_admin
      password: zw58599908@
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

#tymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
  #国际化配置
  messages:
    basename: i18n.login
  #redis缓存配置
  redis:
#    host: localhost
    host: 116.62.155.70
    port: 6379
    password: fkzwmds

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: coms.zhanwang.pojo

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

##日志文件的存放地址(存放位置已在logbcak-spring.xml文档里配置)和日志级别
logging:
#  file: logs/basics_api
  level:
    root: DEBUG








